ingress:
  url: k3s.brokencrystals.nexploit.app
  cert: ""
  authlevel: "."
images: 
  main: experimental
  client: unstable
includeRepeater: false
repeaterImageTag: ""
repeaterID: ""
token: ""
cluster: ""
timeout: ""
