apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: mkwongae-registry-key
      containers:
        - name: nodejs
          image: mkwongae/brokencrystals:{{ .Values.images.main }}
          env:
            - name: URL
              value: "https://{{ .Values.ingress.url }}"
            - name: DATABASE_HOST
              value: "{{ .Release.Name }}-postgres.{{ .Release.Namespace }}.svc.cluster.local"
            - name: DATABASE_SCHEMA
              value: "bc"
            - name: DATABASE_USER
              value: "bc"
            - name: DATABASE_PASSWORD
              value: "bc"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_DEBUG
              value: "true"
            - name: AWS_BUCKET
              value: "https://neuralegion-open-bucket.s3.amazonaws.com"
            - name: GOOGLE_MAPS_API
              value: "AIzaSyD2wIxpYCuNI0Zjt8kChs2hLTS5abVQfRQ"
            - name: JWT_PRIVATE_KEY_LOCATION
              value: "config/keys/jwtRS256.key"
            - name: JWT_PUBLIC_KEY_LOCATION
              value: "config/keys/jwtRS256.key.pub.pem"
            - name: JWT_SECRET_KEY
              value: "1234"
            - name: JWK_PRIVATE_KEY_LOCATION
              value: "config/keys/jwk.key.pem"
            - name: JWK_PUBLIC_KEY_LOCATION
              value: "config/keys/jwk.pub.key.pem"
            - name: JWK_PUBLIC_JSON 
              value: "config/keys/jwk.pub.json"
            - name: JKU_URL
              value: "https://raw.githubusercontent.com/NeuraLegion/brokencrystals/development/config/keys/jku.json"
            - name: X5U_URL
              value: "https://raw.githubusercontent.com/NeuraLegion/brokencrystals/development/config/keys/x509.crt"
          volumeMounts:
          - name: brokencrystals-nginx-proxy
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
          resources:
            requests:
              cpu: 900m
              memory: 1024Mi
            limits:
              memory: 15G
          livenessProbe:
            httpGet:
              path: /api/config
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
      restartPolicy: Always

      volumes:
      - name: brokencrystals-nginx-proxy
        configMap:
          name: brokencrystals-nginx-proxy
