apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}-postgres
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: POSTGRES_DB
              value: "bc"
            - name: POSTGRES_USER
              value: "bc"
            - name: POSTGRES_PASSWORD
              value: "bc"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
          - name: brokencrystals-postgres
            mountPath: /docker-entrypoint-initdb.d/pg.sql
            subPath: pg.sql
            readOnly: true       
      restartPolicy: Always
      volumes:
      - name: brokencrystals-postgres
        configMap:
          name: brokencrystals-postgres
