apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kc-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-kc-db
    app.kubernetes.io/instance: {{ .Release.Name }}-kc-db
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kc-db
      app.kubernetes.io/instance: {{ .Release.Name }}-kc-db
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}-kc-db
        app: {{ .Release.Name }}-kc-db
    spec:
      containers:
        - name: keycloak-postgres
          image: postgres:12.2-alpine
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "password"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi          
          volumeMounts:
          - name: brokencrystals-kc-db
            mountPath: /usr/local/share/postgresql/postgresql.conf.sample
            subPath: postgresql.conf.sample
            readOnly: true
      restartPolicy: Always

      volumes:
      - name: brokencrystals-kc-db
        configMap:
          name: brokencrystals-kc-db
